---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gjgx-sbgj-web
    component: gjgx-sbgj-web
    tier: frontend
  name: gjgx-sbgj-web
  namespace: $PROJECT_NAME
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: gjgx-sbgj-web
      component: gjgx-sbgj-web
      tier: frontend
  template:
    metadata:
      labels:
        app: gjgx-sbgj-web
        component: gjgx-sbgj-web
        tier: frontend
    spec:
      volumes:
        - name: volume-nginxconf
          configMap:
            name: nginx
            items:
              - key: nginx.conf
                path: nginx.conf
            defaultMode: 420
        - name: volume-nginxdefault
          configMap:
            name: nginx
            items:
              - key: default.conf
                path: default.conf
            defaultMode: 420
      containers:
        - env:
            #- name: CACHE_IGNORE
            #  value: js|html
            #- name: CACHE_PUBLIC_EXPIRATION
            #  value: 3d
          image: $REGISTRY/$IMAGE_NAMESPACE/gjgx-sbgj-web:SNAPSHOT-$BUILD_NUMBER
          imagePullPolicy: Always
          name: gjgx-sbgj-web
          ports:
            - containerPort: 80
              protocol: TCP
              name: http-80
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 200Mi
          volumeMounts:
            - name: volume-nginxconf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: volume-nginxdefault
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gjgx-sbgj-web
    component: gjgx-sbgj-web
  name: gjgx-sbgj-web
  namespace: $PROJECT_NAME
spec:
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 8091
  selector:
    app: gjgx-sbgj-web
    component: gjgx-sbgj-web
    tier: frontend
  sessionAffinity: None
  type: NodePort
